"""B4 round-14 live-caught defect (#16) — the first BUILD-layer live event.

Planning run 660d487e reached BUILD_QUEUED (FEAT-1DF4) — the machine-made
spec+plan committed past all oracles — and one second later the Mode B build
intake rejected it:

    pipeline_consumer: originating_adapter=None not in approved list for
    feature_id=FEAT-1DF4; rejecting -> build-failed "originator not recognised"

The pre-dispatch human approval gate (tap 2) was never reached. Root cause:
the B3 planning trigger is contract-legal (``triggered_by="forge-internal"``,
adapter omitted — nats-core's ``BuildQueuedPayload`` validator permits exactly
that), but the consumer's originator gate predated machine dispatch and
treated the human adapter as the only identity. A latent second fault sat one
gate lower: the trigger emitted a REPO-RELATIVE ``feature_yaml_path`` that the
allowlist check resolved against the daemon CWD (pass/fail by accident).

These tests replay the REAL round-14 envelope — captured off the production
B3 trigger closure and committed as
``fixtures/round14_build_queued_660d487e.json`` (fixture rule: generated by
the other side's own code, never hand-reconstructed) — through the REAL
pipeline-consumer handler, and lock the machine-dispatch originator gate
semantics.
"""

from __future__ import annotations

import asyncio
import datetime as dt
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock

import pytest
from nats_core.envelope import EventType, MessageEnvelope
from nats_core.events import BuildQueuedPayload
from pydantic import ValidationError

from forge.adapters.nats.pipeline_consumer import (
    REASON_ORIGINATOR_NOT_RECOGNISED,
    REASON_PATH_OUTSIDE_ALLOWLIST,
    PipelineConsumerDeps,
    handle_message,
)
from forge.config.models import (
    FilesystemPermissions,
    ForgeConfig,
    PermissionsConfig,
    PipelineConfig,
)

# ---------------------------------------------------------------------------
# Run 660d487e logged values (B4 round 14)
# ---------------------------------------------------------------------------

FEATURE_ID = "FEAT-1DF4"
TARGET_REPO = "guardkit/api_test"
BRANCH = "planning/660d487e-37ef-4ae2-a6ef-9505a5fd4acc"
CORRELATION_ID = "660d487e-37ef-4ae2-a6ef-9505a5fd4acc"
ORIGINATING_USER = "U03QR8WKT29"
PLAN_FILES = [
    "tasks/TASK-1DF4-001.md",
    ".guardkit/features/FEAT-1DF4.yaml",
]
#: The live ``planning.target_repo_paths`` mapping for guardkit/api_test and
#: the matching allowlist root the daemon runs with.
CHECKOUT = "/home/richardwoollcott/Projects/appmilla_github/api_test"

#: The absolute feature-YAML path the fixed trigger must emit (repo-relative
#: plan path joined onto the configured checkout).
EXPECTED_FEATURE_YAML_PATH = (
    "/home/richardwoollcott/Projects/appmilla_github/api_test/"
    ".guardkit/features/FEAT-1DF4.yaml"
)

#: The six human adapters — the originator allowlist BEFORE this fix. Used to
#: prove the captured fixture is non-vacuous (the old gate refuses it).
OLD_HUMAN_ONLY_ORIGINATORS = (
    "terminal",
    "voice-reachy",
    "telegram",
    "slack",
    "dashboard",
    "cli-wrapper",
)

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "round14_build_queued_660d487e.json"


class _FixedClock:
    def __call__(self) -> dt.datetime:
        return dt.datetime(2026, 7, 14, 12, 0, 0, tzinfo=dt.timezone.utc)


def _load_fixture_bytes() -> bytes:
    return FIXTURE_PATH.read_bytes()


def _make_msg(data: bytes) -> AsyncMock:
    msg = AsyncMock()
    msg.data = data
    msg.ack = AsyncMock()
    return msg


def _consumer_deps(
    *,
    allowlist: list[Path] | None = None,
    approved_originators: list[str] | None = None,
    is_duplicate_terminal: bool = False,
) -> tuple[PipelineConsumerDeps, dict[str, AsyncMock]]:
    pipeline = (
        PipelineConfig(approved_originators=approved_originators)
        if approved_originators is not None
        else PipelineConfig()  # default list (now includes forge-internal)
    )
    config = ForgeConfig(
        pipeline=pipeline,
        permissions=PermissionsConfig(
            filesystem=FilesystemPermissions(
                allowlist=allowlist if allowlist is not None else [Path(CHECKOUT)]
            ),
        ),
    )
    is_dup = AsyncMock(return_value=is_duplicate_terminal)
    dispatch = AsyncMock()
    publish_failed = AsyncMock()
    deps = PipelineConsumerDeps(
        forge_config=config,
        is_duplicate_terminal=is_dup,
        dispatch_build=dispatch,
        publish_build_failed=publish_failed,
    )
    return deps, {
        "is_duplicate_terminal": is_dup,
        "dispatch_build": dispatch,
        "publish_build_failed": publish_failed,
    }


async def _drive_real_trigger() -> bytes:
    """Re-drive the REAL B3 trigger closure and return the published bytes.

    Mirrors the committed-fixture generator so a test can prove the fixture
    is not stale — the payload the production trigger emits today must still
    match the bytes on disk (modulo the volatile envelope ``message_id`` /
    ``timestamp``).
    """
    import tempfile

    from forge.adapters.sqlite import connect_writer
    from forge.cli._serve_planning import compose_planning_consumer_and_dispatch
    from forge.lifecycle import migrations as lifecycle_migrations
    from tests.integration.conftest import InMemoryNats

    broker = InMemoryNats()
    config = ForgeConfig.model_validate(
        {
            "permissions": {"filesystem": {"allowlist": [CHECKOUT]}},
            "planning": {
                "enabled": True,
                "escalation_approver": "rich",
                "target_terminal": {"enabled": True},
                "target_repo_paths": {TARGET_REPO: CHECKOUT},
            },
        }
    )
    with tempfile.TemporaryDirectory() as td:
        db_path = Path(td) / "replay.db"
        pool = connect_writer(db_path)
        lifecycle_migrations.apply_at_boot(pool)
        result = await compose_planning_consumer_and_dispatch(
            db_path=db_path,
            nats_client=broker,
            config=config,
            clock=_FixedClock(),
        )
        assert result is not None and result.driver is not None
        trigger = result.driver._deps.dispatch_build_trigger
        try:
            outcome = await trigger(
                plan_run_id=CORRELATION_ID,
                correlation_id=CORRELATION_ID,
                feature_id=FEATURE_ID,
                target_repo=TARGET_REPO,
                branch=BRANCH,
                plan_files=PLAN_FILES,
                originating_user=ORIGINATING_USER,
            )
            assert outcome.queued is True
            return broker.published[f"pipeline.build-queued.{FEATURE_ID}"][0]
        finally:
            for task in list(result.background_tasks or []):
                task.cancel()
            await asyncio.gather(
                *(result.background_tasks or []), return_exceptions=True
            )


# ---------------------------------------------------------------------------
# The committed fixture is faithful to the production trigger (non-stale)
# ---------------------------------------------------------------------------


class TestFixtureProvenance:
    def test_committed_fixture_parses_and_carries_the_defect_shape(self) -> None:
        env = MessageEnvelope.model_validate_json(_load_fixture_bytes())
        payload = BuildQueuedPayload.model_validate(env.payload)
        assert payload.feature_id == FEATURE_ID
        assert payload.repo == TARGET_REPO
        assert payload.triggered_by == "forge-internal"
        # The exact shape that tripped the round-14 gate: a machine dispatch
        # with NO originating_adapter.
        assert payload.originating_adapter is None
        assert payload.originating_user == ORIGINATING_USER
        # The second-fault fix: an ABSOLUTE feature_yaml_path.
        assert payload.feature_yaml_path == EXPECTED_FEATURE_YAML_PATH

    @pytest.mark.asyncio
    async def test_committed_fixture_matches_freshly_driven_trigger(self) -> None:
        # Drive the production trigger live and confirm the committed bytes
        # still reflect what it emits today (payload is deterministic under
        # the fixed clock; the envelope message_id/timestamp are volatile).
        fresh = await _drive_real_trigger()
        fresh_env = MessageEnvelope.model_validate_json(fresh)
        committed_env = MessageEnvelope.model_validate_json(_load_fixture_bytes())
        assert fresh_env.payload == committed_env.payload
        assert fresh_env.source_id == committed_env.source_id == "forge"
        assert fresh_env.event_type == committed_env.event_type
        assert fresh_env.correlation_id == committed_env.correlation_id


# ---------------------------------------------------------------------------
# REPLAY — the round-14 envelope through the real consumer handler
# ---------------------------------------------------------------------------


class TestRound14Replay:
    def test_old_gate_would_reject_the_fixture_non_vacuous(self) -> None:
        """Pre-fix regression witness: the OLD originator gate refuses it.

        Replicates the pre-fix predicate (``originating_adapter`` is the only
        identity; the allowlist is the six human adapters) so the captured
        fixture provably reproduces the live defect rather than passing
        vacuously.
        """
        env = MessageEnvelope.model_validate_json(_load_fixture_bytes())
        payload = BuildQueuedPayload.model_validate(env.payload)
        old_originator = payload.originating_adapter
        old_rejected = (
            old_originator is None or old_originator not in OLD_HUMAN_ONLY_ORIGINATORS
        )
        assert old_rejected, (
            "fixture no longer reproduces the round-14 defect — the old "
            "adapter-only gate must refuse this machine dispatch"
        )

    @pytest.mark.asyncio
    async def test_fixed_consumer_passes_gates_and_reaches_dispatch(self) -> None:
        """Post-fix: the same envelope clears gates 2 (originator) AND 3
        (path allowlist) and reaches the dispatch / pre-dispatch-approval
        path — no build-failed, no premature ack."""
        deps, mocks = _consumer_deps()
        msg = _make_msg(_load_fixture_bytes())

        await handle_message(msg, deps)

        # Gate 2 + gate 3 passed: dispatch_build was invoked with the parsed
        # payload (the pre-dispatch approval gate lives inside dispatch_build).
        mocks["dispatch_build"].assert_awaited_once()
        sent_payload = mocks["dispatch_build"].await_args.args[0]
        assert isinstance(sent_payload, BuildQueuedPayload)
        assert sent_payload.feature_id == FEATURE_ID
        assert sent_payload.triggered_by == "forge-internal"
        # No rejection published; the ack is deferred to the state machine.
        mocks["publish_build_failed"].assert_not_called()
        msg.ack.assert_not_called()


# ---------------------------------------------------------------------------
# Machine-dispatch originator gate — jarvis + poisons
# ---------------------------------------------------------------------------


def _payload_dict(**overrides: Any) -> dict[str, Any]:
    base: dict[str, Any] = {
        "feature_id": FEATURE_ID,
        "repo": TARGET_REPO,
        "branch": BRANCH,
        "feature_yaml_path": EXPECTED_FEATURE_YAML_PATH,
        "triggered_by": "forge-internal",
        "originating_adapter": None,
        "originating_user": ORIGINATING_USER,
        "correlation_id": CORRELATION_ID,
        "requested_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "queued_at": dt.datetime.now(dt.timezone.utc).isoformat(),
        "mode": "mode-b",
    }
    base.update(overrides)
    return base


def _envelope_bytes(payload: dict[str, Any]) -> bytes:
    envelope = MessageEnvelope(
        source_id="forge",
        event_type=EventType.BUILD_QUEUED,
        correlation_id=CORRELATION_ID,
        payload=payload,
    )
    return envelope.model_dump_json().encode("utf-8")


class TestMachineDispatchOriginatorGate:
    @pytest.mark.asyncio
    async def test_jarvis_adapter_in_list_is_accepted(self) -> None:
        payload = _payload_dict(
            triggered_by="jarvis",
            originating_adapter="slack",
        )
        deps, mocks = _consumer_deps()
        msg = _make_msg(_envelope_bytes(payload))

        await handle_message(msg, deps)

        mocks["dispatch_build"].assert_awaited_once()
        mocks["publish_build_failed"].assert_not_called()

    def test_jarvis_without_adapter_is_impossible_at_payload_layer(self) -> None:
        """The stricter jarvis invariant is enforced by nats-core's own
        validator, one layer below the consumer — so the consumer never has
        to special-case a None-adapter jarvis build."""
        with pytest.raises(ValidationError):
            BuildQueuedPayload.model_validate(
                _payload_dict(triggered_by="jarvis", originating_adapter=None)
            )

    @pytest.mark.asyncio
    async def test_forge_internal_not_in_custom_config_is_rejected(self) -> None:
        """Config still governs: a deployment whose ``approved_originators``
        omits forge-internal rejects the machine dispatch."""
        deps, mocks = _consumer_deps(approved_originators=["terminal", "cli-wrapper"])
        msg = _make_msg(_envelope_bytes(_payload_dict()))

        await handle_message(msg, deps)

        msg.ack.assert_awaited_once()
        mocks["dispatch_build"].assert_not_called()
        sent, _feature_id = mocks["publish_build_failed"].await_args.args
        assert sent.failure_reason == REASON_ORIGINATOR_NOT_RECOGNISED

    @pytest.mark.asyncio
    async def test_wire_valid_adapter_not_in_policy_is_rejected(self) -> None:
        """An adapter that is valid on the wire (a member of the
        OriginatingAdapter Literal) but not in the deployment's
        ``approved_originators`` policy is rejected by the consumer gate —
        config, not the wire schema, is the final authority."""
        # triggered_by=jarvis satisfies nats-core's adapter-required rule;
        # ``telegram`` is a valid Literal member but absent from the policy.
        payload = _payload_dict(triggered_by="jarvis", originating_adapter="telegram")
        deps, mocks = _consumer_deps(
            approved_originators=["forge-internal", "slack"]
        )
        msg = _make_msg(_envelope_bytes(payload))

        await handle_message(msg, deps)

        msg.ack.assert_awaited_once()
        mocks["dispatch_build"].assert_not_called()
        sent, _feature_id = mocks["publish_build_failed"].await_args.args
        assert sent.failure_reason == REASON_ORIGINATOR_NOT_RECOGNISED

    @pytest.mark.asyncio
    async def test_adapter_precedence_unapproved_adapter_rejected_even_if_triggered_by_approved(
        self,
    ) -> None:
        """Adapter-takes-precedence (stricter reading): when an adapter is
        present it alone is checked — an unapproved adapter is rejected even
        though ``triggered_by`` names an approved layer."""
        # triggered_by=jarvis (kept in the policy) with adapter=slack (NOT in
        # the policy). The effective identity is the adapter, so the build is
        # rejected despite the approved triggered_by layer.
        payload = _payload_dict(triggered_by="jarvis", originating_adapter="slack")
        deps, mocks = _consumer_deps(
            approved_originators=["jarvis", "forge-internal", "terminal"]
        )
        msg = _make_msg(_envelope_bytes(payload))

        await handle_message(msg, deps)

        msg.ack.assert_awaited_once()
        mocks["dispatch_build"].assert_not_called()
        sent, _feature_id = mocks["publish_build_failed"].await_args.args
        assert sent.failure_reason == REASON_ORIGINATOR_NOT_RECOGNISED

    @pytest.mark.asyncio
    async def test_path_outside_allowlist_still_rejected_with_new_semantics(
        self,
    ) -> None:
        """Gate 3 still rejects an absolute path outside the allowlist — the
        machine dispatch now clears gate 2 but a mis-targeted checkout is
        caught at the path gate."""
        payload = _payload_dict(
            feature_yaml_path="/etc/passwd-not-a-checkout/FEAT-1DF4.yaml"
        )
        deps, mocks = _consumer_deps()
        msg = _make_msg(_envelope_bytes(payload))

        await handle_message(msg, deps)

        msg.ack.assert_awaited_once()
        mocks["dispatch_build"].assert_not_called()
        sent, _feature_id = mocks["publish_build_failed"].await_args.args
        assert sent.failure_reason == REASON_PATH_OUTSIDE_ALLOWLIST

    @pytest.mark.asyncio
    async def test_duplicate_terminal_machine_dispatch_is_skipped(self) -> None:
        """Duplicate-terminal skip is unchanged for the machine dispatch: the
        build is acked and NOT dispatched, no failure published."""
        deps, mocks = _consumer_deps(is_duplicate_terminal=True)
        msg = _make_msg(_envelope_bytes(_payload_dict()))

        await handle_message(msg, deps)

        msg.ack.assert_awaited_once()
        mocks["dispatch_build"].assert_not_called()
        mocks["publish_build_failed"].assert_not_called()
