"""A test window for each approved scenario (8 October 2026).

The planner may say a request is already done only when every approved
scenario has a test it was shown and can cite. On a deactivate request it was
shown the tests of the two error scenarios and not the one of the success
scenario, though the repository had it: that window scored below the
documentation's and the error tests', sat in a file already shown, and the
size budget ran out first.

A wrong test shown as a scenario's proof is worse than none, because the
planner may then say "already done" when it is not. So a window is taken as
a scenario's test only on strong evidence, nothing but documentation ever
gives way to one, and a scenario already shown a test takes nothing.

Neutral, made-up files in no real language or test tool: a route table, two
pages of documentation, the request's own file of checks, and other
features' checks under the declared test folders. Nothing here is any real
project's code.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

from forge.planning.code_evidence import (
    MAX_EVIDENCE_WINDOWS,
    choose_windows,
    scenario_words,
    trim_to_budget,
)
from forge.planning.driver import PlanningRunDriver
from forge.planning.repository_facts import LocalCheckoutReader

REQUEST = (
    "Add a PATCH /things/{thing_id}/archive endpoint that archives the thing and "
    "returns it, with 404 for an unknown id and 409 if already archived."
)

SPEC = """# Generated by a writer
@things
Feature: Archive a thing

  Background:
    Given the thing store is available

  # Why: the main path
  @key-example
  Scenario: A thing is successfully archived
    Given a thing "t-1" that is live
    When I send a PATCH request to "/things/t-1/archive"
    Then the request should succeed
    And the returned thing should be marked archived

  @boundary
  Scenario: Archiving an already archived thing returns a conflict
    Given a thing "t-2" that is archived
    When I send a PATCH request to "/things/t-2/archive"
    Then the request should be rejected with a conflict

  @negative
  Scenario: Archiving a never-made thing returns not found
    Given no thing "t-9"
    When I send a PATCH request to "/things/t-9/archive"
    Then the request should be rejected as not found
"""

ROUTES = (
    "table things\n"
    "  route PATCH /things/{thing_id}/archive -> archive_thing\n"
    "    look up the thing by its id, else answer 404 unknown\n"
    "    when the thing is already archived answer 409\n"
    "    mark the thing archived and answer 200 with the thing\n"
)

DOCS = (
    "# Things\n"
    "\n"
    "PATCH /things/{thing_id}/archive archives the thing and returns it.\n"
    "It answers 404 for an unknown id and 409 if the thing is already archived.\n"
    "The endpoint returns the archived thing.\n"
)


def _filler(count: int) -> str:
    return "".join(f"  note {n}\n" for n in range(count))


#: The request's own checks: the two error ones first, the success one well
#: below them, each its own block.
CHECKS = (
    "check never-made thing\n"
    "  call PATCH \"/things/t-9/archive\" with an unknown id\n"
    "  expect 404, not found\n"
    + _filler(3)
    + "\n" * 2
    + _filler(20)
    + "\n"
    + "check already archived thing\n"
    "  call PATCH \"/things/t-2/archive\" when already archived\n"
    "  expect 409 conflict and the thing returns unchanged\n"
    + _filler(3)
    + "\n" * 2
    + _filler(20)
    + "\n"
    + "check live thing\n"
    "  call PATCH \"/things/t-1/archive\"\n"
    "  expect it to succeed: 200, and the returned thing is marked archived\n"
)


def _other_checks(n: int) -> str:
    """Another feature's check that also says ``never-made``: the word only
    the error scenario says is found all over the checks."""
    return (
        f"check widget {n}\n"
        f"  call GET /widgets/never-made-{n} for an unknown id\n"
        "  expect 404, not found\n"
        + _filler(4)
    )


#: Another feature's check that says the success scenario's words and the
#: request's "archive", but never names the request's route.
LOOKALIKE = (
    "check widget archive succeeds\n"
    "  call PUT \"/widgets/w-1/store\" to archive the widget\n"
    "  expect it to succeed, marked live, the thing is archived and returned\n"
)

NOTES = (
    "# Notes\n"
    "\n"
    "The archive route is PATCH /things/{thing_id}/archive.\n"
)

#: An older page that mentions the route in passing, three times.
HISTORY = "".join(
    f"# Release {n}\n\nMentions /archive once.\n" + "\n" * 20 for n in range(1, 4)
)

FILES = {
    "src/things.routes": ROUTES,
    "docs/things.md": DOCS,
    "docs/notes.md": NOTES,
    "docs/history.md": HISTORY,
    "checks/things/archive.checks": CHECKS,
    "checks/widgets/lookalike.checks": LOOKALIKE,
    **{f"checks/widgets/widget_{n}.checks": _other_checks(n) for n in range(1, 9)},
}
TEST_ROOTS = ["checks/things", "checks/widgets"]
SUCCESS_CHECK = "checks/things/archive.checks"


def _line_of(text: str, needle: str) -> int:
    return next(n for n, line in enumerate(text.split("\n"), start=1) if needle in line)


def _success_line() -> int:
    return _line_of(CHECKS, "/things/t-1/archive")


def _shows(windows: list[dict], path: str, line: int) -> bool:
    return any(w["path"] == path and w["first_line"] <= line <= w["last_line"] for w in windows)


def _key(window: dict) -> tuple[str, int, int]:
    return (window["path"], window["first_line"], window["last_line"])


def _git(path: Path, files: dict[str, str]) -> Path:
    env = {
        **os.environ,
        "GIT_AUTHOR_NAME": "t",
        "GIT_AUTHOR_EMAIL": "t@t",
        "GIT_COMMITTER_NAME": "t",
        "GIT_COMMITTER_EMAIL": "t@t",
    }
    for name, text in files.items():
        (path / name).parent.mkdir(parents=True, exist_ok=True)
        (path / name).write_text(text)
    subprocess.run(["git", "init", "-q"], cwd=path, check=True, env=env)
    subprocess.run(["git", "add", "-A"], cwd=path, check=True, env=env)
    subprocess.run(["git", "commit", "-qm", "init"], cwd=path, check=True, env=env)
    return path


@pytest.fixture(scope="module")
def repo(tmp_path_factory: pytest.TempPathFactory) -> Path:
    return _git(tmp_path_factory.mktemp("things"), FILES)


def _windows(
    repo: Path, budget: int, test_roots: list[str], spec: str = SPEC
) -> list[dict]:
    """The windows the planner is shown, chosen and trimmed as the
    descriptor chooses and trims them."""
    found = PlanningRunDriver._where_the_specs_words_already_appear(
        str(repo),
        spec,
        reader=LocalCheckoutReader(str(repo)),
        request_text=REQUEST,
        evidence_chars=budget,
        test_roots=test_roots,
    ) or []
    trim_to_budget(found, [], budget=budget)
    return [w for entry in found for w in entry.get("evidence") or []]


#: Room for some of the windows, not all.
TIGHT = 2_000


def test_scenario_words_are_each_scenarios_own_words() -> None:
    found = scenario_words(SPEC)
    assert [title for title, _words, _values in found] == [
        "A thing is successfully archived",
        "Archiving an already archived thing returns a conflict",
        "Archiving a never-made thing returns not found",
    ]
    _title, success, values = found[0]
    # The title's and the steps' words, by their first five letters.
    assert "succe" in success and "archi" in success and "thing" in success
    # Not the format's words, common English, the tags or the comments.
    for word in ("given", "when", "then", "shoul", "that", "key", "why", "main", "gener"):
        assert word not in success
    # Not the background's words either: they belong to no one scenario.
    assert "avail" not in success
    # A quoted value with punctuation inside is a value, not words.
    assert "/things/t-1/archive" in values
    assert "t-1" not in success
    assert "confl" in found[1][1] and "found" in found[2][1]


def test_scenario_values_come_from_quotes_tables_and_punctuated_names() -> None:
    spec = (
        "Feature: f\n"
        "  Scenario: Odd domains are kept\n"
        "    Given the following users exist:\n"
        "      | email                |\n"
        "      | admin@domain.co.uk   |\n"
        "    When I ask for the list at /users/domains\n"
        '    Then it includes "domain.co.uk" and "inactive"\n'
    )
    [(_title, words, values)] = scenario_words(spec)
    assert {"admin@domain.co.uk", "domain.co.uk", "/users/domains"} <= set(values)
    # A plain quoted word is a word, not a value; the data's pieces are not words.
    assert "inactive" not in values and "inact" in words
    assert "admin" not in words


def test_scenario_words_leave_out_programming_keywords() -> None:
    spec = "Feature: f\n  Scenario: None of it\n    Then null is returned as none, self and class\n"
    [(_title, words, _values)] = scenario_words(spec)
    assert not {"none", "null", "self", "class"} & set(words)


def test_scenario_words_ignore_a_specification_without_scenarios() -> None:
    assert scenario_words("Feature: nothing\n  Background:\n    Given a thing\n") == []
    assert scenario_words("") == []


def test_without_test_folders_the_success_check_is_not_shown(repo: Path) -> None:
    """The defect, in small: the success check sits in a file already
    shown, and the budget goes on one window per file for the word only the
    error scenario says."""
    chosen = _windows(repo, TIGHT, [])
    assert not _shows(chosen, SUCCESS_CHECK, _success_line())
    assert _shows(chosen, "src/things.routes", 2)


def test_each_scenario_is_shown_a_check_when_one_fits(repo: Path) -> None:
    plain = _windows(repo, TIGHT, [])
    chosen = _windows(repo, TIGHT, TEST_ROOTS)
    assert _shows(chosen, SUCCESS_CHECK, _success_line())
    # The code the request names is still shown.
    assert _shows(chosen, "src/things.routes", 2)
    # Only documentation gave way: every test window shown before still is.
    tests_before = {_key(w) for w in plain if w["path"].startswith("checks/")}
    assert tests_before <= {_key(w) for w in chosen}
    went = {_key(w) for w in plain} - {_key(w) for w in chosen}
    assert went and all(path.startswith("docs/") for path, _first, _last in went)
    # Within the same budget and limit.
    assert sum(len(w["text"]) for w in chosen) <= TIGHT
    assert len(chosen) <= MAX_EVIDENCE_WINDOWS
    # The private marks never reach the planner.
    assert all(not key.startswith("_") for w in chosen for key in w)


def test_a_check_that_does_not_name_the_route_is_never_a_scenario_window(repo: Path) -> None:
    """The look-alike says the success scenario's words but tests another
    feature: no window rather than a wrong one."""
    chosen = _windows(repo, 16_000, TEST_ROOTS)
    plain = _windows(repo, 16_000, [])
    lookalike = [w for w in chosen if w["path"] == "checks/widgets/lookalike.checks"]
    assert lookalike == [w for w in plain if w["path"] == "checks/widgets/lookalike.checks"]


def test_a_window_outside_the_test_folders_is_never_a_scenario_window(repo: Path) -> None:
    """With the checks not declared as tests, the scenarios take nothing."""
    plain = _windows(repo, TIGHT, [])
    elsewhere = _windows(repo, TIGHT, ["tests"])
    assert list(map(_key, plain)) == list(map(_key, elsewhere))


def test_with_room_for_everything_nothing_is_lost(repo: Path) -> None:
    plain = _windows(repo, 16_000, [])
    with_scenarios = _windows(repo, 16_000, TEST_ROOTS)
    assert sorted(map(_key, plain)) == sorted(map(_key, with_scenarios))


def test_a_scenario_whose_check_holds_another_scenarios_words_takes_nothing(
    tmp_path: Path,
) -> None:
    """The only check near the success scenario also says "conflict": it may
    be the other scenario's, so it is not taken as the success one's."""
    mixed = CHECKS.replace(
        "expect it to succeed: 200, and the returned thing is marked archived",
        "expect it to succeed: 200, marked archived, never a conflict",
    )
    repo = _git(tmp_path, {**FILES, SUCCESS_CHECK: mixed})
    plain = _windows(repo, TIGHT, [])
    chosen = _windows(repo, TIGHT, TEST_ROOTS)
    assert list(map(_key, plain)) == list(map(_key, chosen))


def test_a_scenario_already_shown_its_check_takes_nothing(repo: Path) -> None:
    """With room for every window, each scenario's check is shown by the
    words' own rounds, so no scenario adds one (and nothing changes)."""
    plain = _windows(repo, 16_000, [])
    assert _shows(plain, SUCCESS_CHECK, _success_line())
    assert sorted(map(_key, plain)) == sorted(map(_key, _windows(repo, 16_000, TEST_ROOTS)))


#: Checks of other routes that name the request's route only in a comment
#: and share the success scenario's example value and words.
RESTORE = (
    "check restoring a thing succeeds\n"
    "  # same shape as /things/{thing_id}/archive, the other way round\n"
    '  thing "t-1" is live again\n'
    '  call PATCH "/things/t-1/restore"\n'
    "  expect it to succeed: 200, and the returned thing is marked live\n"
)
ENABLE = (
    "check enabling a thing succeeds\n"
    "  # mirrors /things/{thing_id}/archive\n"
    '  thing "t-1" is live again\n'
    '  call POST "/admin/t-1/enable"\n'
    "  expect it to succeed: 200, and the returned thing is marked live\n"
)
LOOKALIKES = {
    "in a file of its own": {"checks/things/restore.checks": RESTORE},
    "after the success check": {SUCCESS_CHECK: CHECKS + "\n" * 2 + _filler(20) + "\n" + RESTORE},
    "for another route": {SUCCESS_CHECK: CHECKS + "\n" * 2 + _filler(20) + "\n" + ENABLE},
}


@pytest.mark.parametrize("where", sorted(LOOKALIKES))
def test_a_check_naming_the_route_only_in_a_comment_is_never_the_scenarios_test(
    tmp_path: Path, where: str
) -> None:
    """The look-alike shares the success scenario's example value and words,
    and names the request's route only in a comment. The real success check
    is shown; the look-alike is never taken as the scenario's test (it is
    shown only as the words' own rounds already show it)."""
    files = {**FILES, **LOOKALIKES[where]}
    repo = _git(tmp_path, files)
    budget = 2_400  # room for the success check once documentation gives way
    plain = _windows(repo, budget, [])
    chosen = _windows(repo, budget, TEST_ROOTS)
    assert not _shows(plain, SUCCESS_CHECK, _success_line())
    assert _shows(chosen, SUCCESS_CHECK, _success_line())
    text = files[SUCCESS_CHECK] if where != "in a file of its own" else RESTORE
    path = SUCCESS_CHECK if where != "in a file of its own" else "checks/things/restore.checks"
    lookalike_line = _line_of(text, "same shape as" if "same shape as" in text else "mirrors")
    added = {_key(w) for w in chosen} - {_key(w) for w in plain}
    assert not any(
        p == path and first <= lookalike_line + 3 and last >= lookalike_line
        for p, first, last in added
    )


def test_example_data_alone_does_not_make_a_check_the_scenarios_test(tmp_path: Path) -> None:
    """A check that holds the success scenario's example value and the
    route, quoted, but none of its words, is not taken as its test."""
    data_only = (
        "check something else\n"
        '  call PATCH "/things/t-1/archive"\n'
        "  expect 200\n"
    )
    repo = _git(tmp_path, {**FILES, SUCCESS_CHECK: CHECKS.replace(
        "check live thing\n"
        '  call PATCH "/things/t-1/archive"\n'
        "  expect it to succeed: 200, and the returned thing is marked archived\n",
        data_only,
    )})
    plain = _windows(repo, TIGHT, [])
    chosen = _windows(repo, TIGHT, TEST_ROOTS)
    assert list(map(_key, plain)) == list(map(_key, chosen))


def test_scenario_words_leave_out_more_programming_keywords() -> None:
    spec = (
        "Feature: f\n  Scenario: s\n"
        "    Then match case switch record using lambda equals select range\n"
    )
    [(_title, words, _values)] = scenario_words(spec)
    assert words == []


def _window(path: str, first: int, text: str, score: int = 1) -> dict:
    return {"path": path, "first_line": first, "last_line": first + 1, "score": score,
            "text": text, "_hit": first}


def test_scenario_windows_take_at_most_half_the_budget() -> None:
    """Four scenarios each fit their own check, but together they may take
    only half of the characters."""
    words = [("northern", "nightly"), ("southern", "sunny"), ("eastward", "early"), ("westward", "windy")]
    checks = [
        _window("checks/a.checks", 10 * n, f"{10 * n}: GO \"/route\" {a} {b} " + "x" * 80)
        for n, (a, b) in enumerate(words, start=1)
    ]
    docs = [_window("docs/a.md", 10 * n, f"{10 * n}: /route " + "y" * 80, score=5) for n in range(1, 5)]
    entries = [{"words": "/route"}]
    choose_windows(
        entries,
        [docs + checks],
        [[(w["path"], w["first_line"]) for w in docs + checks]],
        from_request=[True],
        max_chars=440,
        scenarios=[([a[:5], b[:5]], []) for a, b in words],
        test_roots=["checks"],
        anchors=["/route"],
        may_give_way=lambda path: path.startswith("docs/"),
    )
    marked = [w for w in entries[0]["evidence"] if w.get("_scenario")]
    assert marked
    assert sum(len(w["text"]) for w in marked) <= 220
    assert all(w["path"] == "checks/a.checks" for w in marked)


def test_a_weaker_test_already_shown_does_not_block_a_stronger_one() -> None:
    """A check already shown holds two of the scenario's words; another
    holds three. The stronger one is added, in place of documentation."""
    doc_a = _window("docs/a.md", 1, '1: "/route" ' + "a" * 90, score=9)
    weak = _window("checks/a.checks", 10, '10: GO "/route" alpha beta ' + "w" * 70, score=8)
    doc_b = _window("docs/b.md", 1, '1: "/route" ' + "b" * 90, score=7)
    strong = _window("checks/a.checks", 40, '40: GO "/route" alpha beta gamma ' + "s" * 64, score=1)
    windows = [doc_a, weak, doc_b, strong]
    entries = [{"words": "/route"}]
    choose_windows(
        entries,
        [windows],
        [[(w["path"], w["first_line"]) for w in windows]],
        from_request=[True],
        max_chars=3 * 110,
        scenarios=[(["alpha", "beta", "gamma"], [])],
        test_roots=["checks"],
        anchors=["/route"],
        may_give_way=lambda path: path.startswith("docs/"),
    )
    shown = {(w["path"], w["first_line"]) for w in entries[0]["evidence"]}
    assert ("checks/a.checks", 40) in shown
    assert ("checks/a.checks", 10) in shown  # a test never gives way
    assert ("docs/b.md", 1) not in shown


def test_the_trim_drops_a_scenario_window_last() -> None:
    low = {"path": "a", "first_line": 1, "last_line": 2, "score": 1, "text": "x" * 10,
           "_scenario": True, "_covers": 1, "_covers_other": {}}
    high = {"path": "b", "first_line": 1, "last_line": 2, "score": 9, "text": "y" * 10,
            "_covers": 1, "_covers_other": {}}
    entries = [{"words": "w", "evidence": [low, high]}]
    trim_to_budget(entries, [], budget=15)
    assert [w["path"] for w in entries[0]["evidence"]] == ["a"]
    assert "_scenario" not in entries[0]["evidence"][0]
