"""A test window for each approved scenario (8 October 2026).

The planner may say a request is already done only when every approved
scenario has a test it was shown and can cite. On a deactivate request it was
shown the tests of the two error scenarios and not the one of the success
scenario, though the repository had it: that window scored below the
documentation's and the error tests', sat in a file already shown, and the
size budget ran out first.

Neutral, made-up files in no real language or test tool: a route table, a
page of documentation, the request's own file of checks, and other features'
checks under the declared test folders. Nothing here is any real project's
code.
"""

from __future__ import annotations

import os
import subprocess
from pathlib import Path

import pytest

from forge.planning.code_evidence import (
    MAX_EVIDENCE_WINDOWS,
    choose_windows,
    scenario_words,
    trim_to_budget,
)
from forge.planning.driver import PlanningRunDriver
from forge.planning.repository_facts import LocalCheckoutReader

REQUEST = (
    "Add a PATCH /things/{thing_id}/archive endpoint that archives the thing and "
    "returns it, with 404 for an unknown id and 409 if already archived."
)

SPEC = """# Generated by a writer
@things
Feature: Archive a thing

  Background:
    Given the thing store is available

  # Why: the main path
  @key-example
  Scenario: A thing is successfully archived
    Given a thing "t-1" that is live
    When I send a PATCH request to "/things/t-1/archive"
    Then the request should succeed
    And the returned thing should be marked archived

  @boundary
  Scenario: Archiving an already archived thing returns a conflict
    Given a thing "t-2" that is archived
    When I send a PATCH request to "/things/t-2/archive"
    Then the request should be rejected with a conflict

  @negative
  Scenario: Archiving a never-made thing returns not found
    Given no thing "t-9"
    When I send a PATCH request to "/things/t-9/archive"
    Then the request should be rejected as not found
"""

ROUTES = (
    "table things\n"
    "  route PATCH /things/{thing_id}/archive -> archive_thing\n"
    "    look up the thing by its id, else answer 404 unknown\n"
    "    when the thing is already archived answer 409\n"
    "    mark the thing archived and answer 200 with the thing\n"
)

DOCS = (
    "# Things\n"
    "\n"
    "PATCH /things/{thing_id}/archive archives the thing and returns it.\n"
    "It answers 404 for an unknown id and 409 if the thing is already archived.\n"
    "The endpoint returns the archived thing.\n"
)


def _filler(count: int) -> str:
    return "".join(f"  note {n}\n" for n in range(count))


#: The request's own checks: the two error ones first, the success one well
#: below them, each its own block.
CHECKS = (
    "check never-made thing\n"
    "  call PATCH /things/t-9/archive with an unknown id\n"
    "  expect 404, not found\n"
    + _filler(3)
    + "\n" * 2
    + _filler(20)
    + "\n"
    + "check already archived thing\n"
    "  call PATCH /things/t-2/archive when already archived\n"
    "  expect 409 conflict and the thing returns unchanged\n"
    + _filler(3)
    + "\n" * 2
    + _filler(20)
    + "\n"
    + "check live thing\n"
    "  call PATCH /things/t-1/archive\n"
    "  expect it to succeed: 200, and the returned thing is marked archived\n"
)


def _other_checks(n: int) -> str:
    """Another feature's check that also says ``never-made``: the word only
    the error scenario says is found all over the checks."""
    return (
        f"check widget {n}\n"
        f"  call GET /widgets/never-made-{n} for an unknown id\n"
        "  expect 404, not found\n"
        + _filler(4)
    )


FILES = {
    "src/things.routes": ROUTES,
    "docs/things.md": DOCS,
    "checks/things/archive.checks": CHECKS,
    **{f"checks/widgets/widget_{n}.checks": _other_checks(n) for n in range(1, 9)},
}
TEST_ROOTS = ["checks/things", "checks/widgets"]
SUCCESS_CHECK = "checks/things/archive.checks"


def _success_line() -> int:
    lines = CHECKS.split("\n")
    return next(n for n, line in enumerate(lines, start=1) if "/things/t-1/archive" in line)


def _shows(windows: list[dict], path: str, line: int) -> bool:
    return any(w["path"] == path and w["first_line"] <= line <= w["last_line"] for w in windows)


def _key(window: dict) -> tuple[str, int, int]:
    return (window["path"], window["first_line"], window["last_line"])


@pytest.fixture(scope="module")
def repo(tmp_path_factory: pytest.TempPathFactory) -> Path:
    path = tmp_path_factory.mktemp("things")
    env = {
        **os.environ,
        "GIT_AUTHOR_NAME": "t",
        "GIT_AUTHOR_EMAIL": "t@t",
        "GIT_COMMITTER_NAME": "t",
        "GIT_COMMITTER_EMAIL": "t@t",
    }
    for name, text in FILES.items():
        (path / name).parent.mkdir(parents=True, exist_ok=True)
        (path / name).write_text(text)
    subprocess.run(["git", "init", "-q"], cwd=path, check=True, env=env)
    subprocess.run(["git", "add", "-A"], cwd=path, check=True, env=env)
    subprocess.run(["git", "commit", "-qm", "init"], cwd=path, check=True, env=env)
    return path


def _windows(repo: Path, budget: int, test_roots: list[str]) -> list[dict]:
    """The windows the planner is shown, chosen and trimmed as the
    descriptor chooses and trims them."""
    found = PlanningRunDriver._where_the_specs_words_already_appear(
        str(repo),
        SPEC,
        reader=LocalCheckoutReader(str(repo)),
        request_text=REQUEST,
        evidence_chars=budget,
        test_roots=test_roots,
    ) or []
    trim_to_budget(found, [], budget=budget)
    return [w for entry in found for w in entry.get("evidence") or []]


#: Room for some of the windows, not all.
TIGHT = 1_600


def test_scenario_words_are_each_scenarios_own_words() -> None:
    found = scenario_words(SPEC)
    assert [title for title, _ in found] == [
        "A thing is successfully archived",
        "Archiving an already archived thing returns a conflict",
        "Archiving a never-made thing returns not found",
    ]
    success = found[0][1]
    # The title's and the steps' words, by their first five letters.
    assert "succe" in success and "archi" in success and "thing" in success
    # Not the format's own words, the tags or the comments.
    for word in ("given", "when", "then", "shoul", "key", "why", "main", "gener"):
        assert word not in success
    # Not the background's words either: they belong to no one scenario.
    assert "avail" not in success
    assert "confl" in found[1][1] and "found" in found[2][1]


def test_scenario_words_ignore_a_specification_without_scenarios() -> None:
    assert scenario_words("Feature: nothing\n  Background:\n    Given a thing\n") == []
    assert scenario_words("") == []


def test_without_test_folders_the_success_check_is_not_shown(repo: Path) -> None:
    """The defect, in small: the success check sits in a file already
    shown, and the budget goes on one window per file for the word only the
    error scenario says."""
    chosen = _windows(repo, TIGHT, [])
    assert not _shows(chosen, SUCCESS_CHECK, _success_line())
    assert _shows(chosen, "src/things.routes", 2)


def test_each_scenario_is_shown_a_check_when_one_fits(repo: Path) -> None:
    chosen = _windows(repo, TIGHT, TEST_ROOTS)
    assert _shows(chosen, SUCCESS_CHECK, _success_line())
    # The code the request names is still shown.
    assert _shows(chosen, "src/things.routes", 2)
    # Within the same budget and limit.
    assert sum(len(w["text"]) for w in chosen) <= TIGHT
    assert len(chosen) <= MAX_EVIDENCE_WINDOWS
    # The private marks never reach the planner.
    assert all(not key.startswith("_") for w in chosen for key in w)


def test_with_room_for_everything_nothing_is_lost(repo: Path) -> None:
    plain = _windows(repo, 16_000, [])
    with_scenarios = _windows(repo, 16_000, TEST_ROOTS)
    assert sorted(map(_key, plain)) == sorted(map(_key, with_scenarios))


def test_a_window_outside_the_test_folders_is_never_a_scenario_window(repo: Path) -> None:
    """With the checks not declared as tests, the scenarios take nothing."""
    plain = _windows(repo, TIGHT, [])
    elsewhere = _windows(repo, TIGHT, ["tests"])
    assert list(map(_key, plain)) == list(map(_key, elsewhere))


def _window(path: str, first: int, text: str, score: int = 1) -> dict:
    return {"path": path, "first_line": first, "last_line": first + 1, "score": score,
            "text": text, "_hit": first}


def test_scenario_windows_take_at_most_half_the_budget() -> None:
    """Four scenarios each fit their own check, but together they may take
    only half of the characters; the rest are left to the other windows."""
    words = ["northern", "southern", "eastward", "westward"]
    checks = [
        _window("checks/a.checks", 10 * n, f"{10 * n}: {word} " + "x" * 90)
        for n, word in enumerate(words, start=1)
    ]
    entries = [{"words": "w"}]
    choose_windows(
        entries,
        [checks],
        [[(w["path"], w["first_line"]) for w in checks]],
        from_request=[True],
        max_chars=440,
        scenarios=[[word[:5]] for word in words],
        test_roots=["checks"],
    )
    marked = [w for w in entries[0]["evidence"] if w.get("_scenario")]
    assert marked
    assert sum(len(w["text"]) for w in marked) <= 220


def test_the_trim_drops_a_scenario_window_last() -> None:
    low = {"path": "a", "first_line": 1, "last_line": 2, "score": 1, "text": "x" * 10,
           "_scenario": True, "_covers": 1, "_covers_other": {}}
    high = {"path": "b", "first_line": 1, "last_line": 2, "score": 9, "text": "y" * 10,
            "_covers": 1, "_covers_other": {}}
    entries = [{"words": "w", "evidence": [low, high]}]
    trim_to_budget(entries, [], budget=15)
    assert [w["path"] for w in entries[0]["evidence"]] == ["a"]
    assert "_scenario" not in entries[0]["evidence"][0]
