# Generated by /feature-spec
# Feature: Uptime Endpoint
# Stack: python
# Assumptions: 5 (see uptime-endpoint_assumptions.yaml)
# Generated: 2026-07-09T14:32:00Z

@uptime-endpoint
Feature: Uptime Endpoint
  As a service operator or monitoring system
  I want a GET /uptime endpoint that returns service identity, start time, and uptime duration
  So that I can verify the service is alive and measure how long it has been running

  Background:
    Given the api_test service is running
    And the uptime endpoint is configured

  # Why: Core happy path — confirms the endpoint returns valid JSON with all three required fields
  @key-example @smoke
  Scenario: The uptime endpoint returns a valid response with service name, start time, and uptime
    When I request the uptime endpoint
    Then the request should succeed
    And the response should be valid JSON
    And the response should contain a service name field
    And the response should contain a start time field in UTC ISO-8601 format
    And the response should contain an uptime seconds field as a numeric value

  # Why: Boundary — uptime at exactly zero seconds (immediate restart)
  @boundary
  Scenario: The uptime endpoint reports zero uptime immediately after start
    When I request the uptime endpoint immediately after the service starts
    Then the request should succeed
    And the uptime seconds field should be zero or a very small positive number

  # Why: Negative — accessing a non-existent endpoint returns not found
  @negative
  Scenario: Requesting a non-existent endpoint returns not found
    When I request a non-existent endpoint
    Then the request should be rejected with a not found status

  # Why: Negative — the endpoint must not access any database
  @negative
  Scenario: The uptime endpoint operates without database access
    When I request the uptime endpoint
    Then the request should succeed
    And the endpoint should not perform any database queries

  # Why: Negative — the endpoint must respond within the stated constraint
  @negative
  Scenario: The uptime endpoint responds within the 100ms constraint
    When I request the uptime endpoint
    Then the response should arrive within 100 milliseconds

  # Why: Negative — malformed or unexpected HTTP methods should be rejected
  @negative
  Scenario: Non-GET requests to the uptime endpoint are rejected
    When I send a non-GET request to the uptime endpoint
    Then the request should be rejected with a method not allowed status

  # Why: Negative — the response must be valid JSON even on error paths
  @negative
  Scenario: Error responses from the uptime endpoint are still valid JSON
    When the uptime endpoint encounters an error
    Then the error response should be valid JSON

  # Why: Edge case — rapid successive requests should all succeed
  @edge-case
  Scenario: Rapid successive requests to the uptime endpoint all succeed
    When I send multiple rapid requests to the uptime endpoint
    Then all requests should succeed
    And each response should contain a valid uptime value

  # Why: Edge case — uptime should continue increasing across requests
  @edge-case
  Scenario: Uptime value increases across successive requests
    When I request the uptime endpoint at time T1
    And I request the uptime endpoint at time T2 (where T2 > T1)
    Then the uptime at T2 should be greater than or equal to the uptime at T1
